require('maps')
require('plugins')
require('settings')

require('text')
require('color')
require('p-lsp')
require('p-cmp')
require('p-pairs')
--require('p-null')
require('p-tree')
require('p-snip')
require('p-mason')
require('p-lualine')
require('p-lspkind')
require('p-telescope')
require('p-treesitter')
